2021-01-10 16:46:45,716 ERROR 93098 [-/127.0.0.1/-/10ms GET /admin/checkLogin] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'react_blog.admin_user' doesn't exist
    at Query.Sequence._packetToError (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    sql:  SELECT userName FROM admin_user WHERE userName = 'undefined' AND password = 'undefined'
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'react_blog.admin_user' doesn't exist"
sqlState: "42S02"
index: 0
sql: " SELECT userName FROM admin_user WHERE userName = 'undefined' AND password = 'undefined'"
name: "ER_NO_SUCH_TABLEError"
pid: 93098
hostname: 192.168.0.103

2021-01-11 15:06:00,966 ERROR 15758 [-/127.0.0.1/-/27ms POST /admin/addArticle] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'article_content' in 'field list'
    at Query.Sequence._packetToError (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    sql: INSERT INTO `article`(`type_id`, `title`, `article_content`, `introduce`, `addTime`, `view_count`) VALUES(1, '测试文章标题', '测试添加文章', '测试简介', 1610467200, 1093)
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'article_content' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `article`(`type_id`, `title`, `article_content`, `introduce`, `addTime`, `view_count`) VALUES(1, '测试文章标题', '测试添加文章', '测试简介', 1610467200, 1093)"
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 15758
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-01-11 15:08:57,412 ERROR 15758 [-/127.0.0.1/-/2ms POST /admin/addArticle] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Query.Sequence._packetToError (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    sql: INSERT INTO `article`(`type_id`, `title`, `article_content`, `introduce`, `addTime`, `view_count`) VALUES(2, '测试文章标题2', '测试添加文章2', '测试简介2', 1610467200, 1073)
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'id' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `article`(`type_id`, `title`, `article_content`, `introduce`, `addTime`, `view_count`) VALUES(2, '测试文章标题2', '测试添加文章2', '测试简介2', 1610467200, 1073)"
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_NO_DEFAULT_FOR_FIELDError"
pid: 15758
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-01-11 15:52:40,485 ERROR 17354 [-/127.0.0.1/-/2ms GET /admin/getArticleList] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:50:10)
    at RDSClient.createPromise [as update] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:30:15)
    at homeController.updateArticle (/Users/shenyuxiaoyao/Desktop/code/react/service/app/controller/admin/home.js:57:41)
    at Object.callFn (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)

pid: 17354
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-01-11 15:53:36,207 ERROR 17354 [-/127.0.0.1/-/0ms GET /admin/getArticleList] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:50:10)
    at RDSClient.createPromise [as update] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:30:15)
    at homeController.updateArticle (/Users/shenyuxiaoyao/Desktop/code/react/service/app/controller/admin/home.js:57:41)
    at Object.callFn (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)

pid: 17354
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-01-11 15:55:40,892 ERROR 17354 [-/127.0.0.1/-/1ms GET /admin/getArticleList] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:50:10)
    at RDSClient.createPromise [as update] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:30:15)
    at homeController.updateArticle (/Users/shenyuxiaoyao/Desktop/code/react/service/app/controller/admin/home.js:57:41)
    at Object.callFn (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 17354
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-01-11 15:58:33,109 ERROR 17558 [-/127.0.0.1/-/7ms GET /admin/getArticleList] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:50:10)
    at RDSClient.createPromise [as update] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:30:15)
    at homeController.updateArticle (/Users/shenyuxiaoyao/Desktop/code/react/service/app/controller/admin/home.js:57:41)
    at Object.callFn (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)

pid: 17558
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-01-11 16:04:50,286 ERROR 17807 [-/127.0.0.1/-/12ms GET /admin/getArticleList] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.introduce as introduce,FROM_UNIXTIME(article.addTime,'%Y-%m-%d' ) as addTime,ty' at line 1
    at Query.Sequence._packetToError (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:65:19)
    at /Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/co/index.js:54:5
    sql: SELECT article.id as id,article.title as title,article.view_count as view_countarticle.introduce as introduce,FROM_UNIXTIME(article.addTime,'%Y-%m-%d' ) as addTime,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.Id ORDER BY article.id DESC 
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.introduce as introduce,FROM_UNIXTIME(article.addTime,'%Y-%m-%d' ) as addTime,ty' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT article.id as id,article.title as title,article.view_count as view_countarticle.introduce as introduce,FROM_UNIXTIME(article.addTime,'%Y-%m-%d' ) as addTime,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.Id ORDER BY article.id DESC "
name: "ER_PARSE_ERRORError"
pid: 17807
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-01-14 23:36:49,053 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 86154ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-14 23:38:57,014 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 98513ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-14 23:40:16,108 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 79089ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-14 23:43:47,145 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 211034ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-14 23:54:20,722 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 582369ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-14 23:57:37,600 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 196870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:00:58,808 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 201205ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:04:41,347 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 222533ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:07:47,244 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 108328ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:11:31,311 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 204015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:20:27,520 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 536204ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:26:16,598 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 349073ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:28:29,773 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 133169ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:29:41,662 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 71885ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:40:50,347 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 668682ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:49:02,280 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 491932ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:52:32,563 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 210278ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:56:45,372 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 232750ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 00:59:15,716 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 150337ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

2021-01-15 09:26:24,502 ERROR 32679 nodejs.ClusterClientNoResponseError: client no response in 30390845ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/code/react/service/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 32679
hostname: 192.168.0.103

